[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/nordic.toml"]

[window]
decorations = "None"
padding = { x = 6, y = 0 }
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 18

[mouse]
hide_when_typing = true
